version: '3.8'

services:
  # Local Redis for development/testing
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # XMRT DAO Ecosystem API
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MESH_PORT=simulate
      - MESH_UPDATE_INTERVAL=30
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  redis_data:
